### ISSUE TITLE
Tes membuat issue untuk pelatihan

### ISSUE THREAD

**Issue by lucernae** [inasafe/inasafe-realtime#135]
Terdapat error di 

rancher server: rancher.bnpb.go.id:8080
environment: inasafe staging
stack: inasafe-django
service/container: inasafe-django-inasafe-worker-1

CC:
@lucernae

```
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/operations.py", line 434, in postgis_version_tuple
11/21/2017 1:22:07 PM    version = self.postgis_lib_version()
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/operations.py", line 414, in postgis_lib_version
11/21/2017 1:22:07 PM    return self._get_postgis_func('postgis_lib_version')
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/operations.py", line 404, in _get_postgis_func
11/21/2017 1:22:07 PM    with self.connection.temporary_connection() as cursor:
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
11/21/2017 1:22:07 PM    return self.gen.next()
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 543, in temporary_connection
11/21/2017 1:22:07 PM    cursor = self.cursor()
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 167, in cursor
11/21/2017 1:22:07 PM    cursor = utils.CursorWrapper(self._cursor(), self)
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 138, in _cursor
11/21/2017 1:22:07 PM    self.ensure_connection()
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
11/21/2017 1:22:07 PM    self.connect()
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
11/21/2017 1:22:07 PM    six.reraise(dj_exc_type, dj_exc_value, traceback)
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
11/21/2017 1:22:07 PM    self.connect()
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 122, in connect
11/21/2017 1:22:07 PM    self.connection = self.get_new_connection(conn_params)
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
11/21/2017 1:22:07 PM    connection = Database.connect(**conn_params)
11/21/2017 1:22:07 PM  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
11/21/2017 1:22:07 PM    conn = _connect(dsn, connection_factory=connection_factory, async=async)
11/21/2017 1:22:07 PMdjango.db.utils.OperationalError: could not connect to server: Connection refused
11/21/2017 1:22:07 PM	Is the server running on host "db" (10.42.169.147) and accepting
11/21/2017 1:22:07 PM	TCP/IP connections on port 5432?
11/21/2017 1:22:07 PM
11/21/2017 1:22:16 PM[2017-11-21 06:22:16,519: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
11/21/2017 1:22:16 PM[2017-11-21 06:22:16,530: INFO/MainProcess] mingle: searching for neighbors
11/21/2017 1:22:17 PM[2017-11-21 06:22:17,540: INFO/MainProcess] mingle: all alone
11/21/2017 1:22:17 PM[2017-11-21 06:22:17,562: WARNING/MainProcess] celery@inasafe-django.628ad06f0bfd ready.
11/21/2017 1:22:17 PM[2017-11-21 06:22:17,563: INFO/MainProcess] Received task: realtime.tasks.flood.create_flood_report[100d0ba7-4619-4b60-b772-8157901664fb]
11/21/2017 1:22:17 PM[2017-11-21 06:22:17,565: INFO/MainProcess] Received task: realtime.tasks.ash.check_processing_task[46e04b4e-d40e-4165-9b68-f61dd43c9372]
11/21/2017 1:22:33 PM[2017-11-21 06:22:33,487: ERROR/MainProcess] Task realtime.tasks.flood.create_flood_report[100d0ba7-4619-4b60-b772-8157901664fb] raised unexpected: error(error(113, 'No route to host'),)
11/21/2017 1:22:33 PMTraceback (most recent call last):
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
11/21/2017 1:22:33 PM    R = retval = fun(*args, **kwargs)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
11/21/2017 1:22:33 PM    return self.run(*args, **kwargs)
11/21/2017 1:22:33 PM  File "/home/web/django_project/realtime/tasks/flood.py", line 254, in create_flood_report
11/21/2017 1:22:33 PM    process_flood.delay()
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 461, in delay
11/21/2017 1:22:33 PM    return self.apply_async(args, kwargs)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/task.py", line 573, in apply_async
11/21/2017 1:22:33 PM    **dict(self._get_exec_options(), **options)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
11/21/2017 1:22:33 PM    reply_to=reply_to or self.oid, **options
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
11/21/2017 1:22:33 PM    **kwargs
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
11/21/2017 1:22:33 PM    routing_key, mandatory, immediate, exchange, declare)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 470, in _ensured
11/21/2017 1:22:33 PM    interval_max)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 382, in ensure_connection
11/21/2017 1:22:33 PM    interval_start, interval_step, interval_max, callback)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
11/21/2017 1:22:33 PM    return fun(*args, **kwargs)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 250, in connect
11/21/2017 1:22:33 PM    return self.connection
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 756, in connection
11/21/2017 1:22:33 PM    self._connection = self._establish_connection()
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/connection.py", line 711, in _establish_connection
11/21/2017 1:22:33 PM    conn = self.transport.establish_connection()
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
11/21/2017 1:22:33 PM    conn = self.Connection(**opts)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 165, in __init__
11/21/2017 1:22:33 PM    self.transport = self.Transport(host, connect_timeout, ssl)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/amqp/connection.py", line 186, in Transport
11/21/2017 1:22:33 PM    return create_transport(host, connect_timeout, ssl)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 299, in create_transport
11/21/2017 1:22:33 PM    return TCPTransport(host, connect_timeout)
11/21/2017 1:22:33 PM  File "/usr/local/lib/python2.7/site-packages/amqp/transport.py", line 95, in __init__
11/21/2017 1:22:33 PM    raise socket.error(last_err)
11/21/2017 1:22:33 PMerror: [Errno 113] No route to host
11/21/2017 1:22:33 PM[2017-11-21 06:22:33,495: INFO/MainProcess] Received task: realtime.tasks.earthquake.retrieve_felt_earthquake_list[45d52ee7-77e6-4002-9178-c6b8e8b88afc]
11/21/2017 1:22:33 PM[2017-11-21 06:22:33,721: INFO/MainProcess] Task realtime.tasks.ash.check_processing_task[46e04b4e-d40e-4165-9b68-f61dd43c9372] succeeded in 0.229666284999s: None
11/21/2017 1:22:34 PM[2017-11-21 06:22:34,238: INFO/MainProcess] Task realtime.tasks.earthquake.retrieve_felt_earthquake_list[45d52ee7-77e6-4002-9178-c6b8e8b88afc] succeeded in 0.516176626s: None
11/21/2017 1:22:36 PMSentry responded with an error: HTTP Error 502: Bad Gateway (url: http://sentry.kartoza.com/api/13/store/)
11/21/2017 1:22:36 PMTraceback (most recent call last):
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/site-packages/raven/transport/threaded.py", line 174, in send_sync
11/21/2017 1:22:36 PM    super(ThreadedHTTPTransport, self).send(data, headers)
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/site-packages/raven/transport/http.py", line 47, in send
11/21/2017 1:22:36 PM    ca_certs=self.ca_certs,
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/site-packages/raven/utils/http.py", line 66, in urlopen
11/21/2017 1:22:36 PM    return opener.open(url, data, timeout)
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/urllib2.py", line 435, in open
11/21/2017 1:22:36 PM    response = meth(req, response)
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/urllib2.py", line 548, in http_response
11/21/2017 1:22:36 PM    'http', request, response, code, msg, hdrs)
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/urllib2.py", line 473, in error
11/21/2017 1:22:36 PM    return self._call_chain(*args)
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
11/21/2017 1:22:36 PM    result = func(*args)
11/21/2017 1:22:36 PM  File "/usr/local/lib/python2.7/urllib2.py", line 556, in http_error_default
11/21/2017 1:22:36 PM    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
11/21/2017 1:22:36 PMHTTPError: HTTP Error 502: Bad Gateway
11/21/2017 1:22:36 PM[u'error: [Errno 113] No route to host', u'  File "celery/app/trace.py", line 240, in trace_task', u'  File "celery/app/trace.py", line 438, in __protected_call__', u'  File "realtime/tasks/flood.py", line 254, in create_flood_report', u'  File "celery/app/task.py", line 461, in delay', u'  File "celery/app/task.py", line 573, in apply_async', u'  File "celery/app/base.py", line 354, in send_task', u'  File "celery/app/amqp.py", line 310, in publish_task', u'  File "kombu/messaging.py", line 172, in publish', u'  File "kombu/connection.py", line 470, in _ensured', u'  File "kombu/connection.py", line 382, in ensure_connection', u'  File "kombu/utils/__init__.py", line 246, in retry_over_time', u'  File "kombu/connection.py", line 250, in connect', u'  File "kombu/connection.py", line 756, in connection', u'  File "kombu/connection.py", line 711, in _establish_connection', u'  File "kombu/transport/pyamqp.py", line 116, in establish_connection', u'  File "amqp/connection.py", line 165, in __init__', u'  File "amqp/connection.py", line 186, in Transport', u'  File "amqp/transport.py", line 299, in create_transport', u'  File "amqp/transport.py", line 95, in __init__']
11/21/2017 1:23:00 PM[2017-11-21 06:23:00,003: INFO/MainProcess] Received task: realtime.tasks.ash.check_processing_task[caa4b8d9-e908-45bb-b910-6210ee5456d8]
11/21/2017 1:23:00 PM[2017-11-21 06:23:00,164: INFO/MainProcess] Task realtime.tasks.ash.check_processing_task[caa4b8d9-e908-45bb-b910-6210ee5456d8] succeeded in 0.159456101001s: None
```

**Comment by cefs29** [comment]
Test Comment
